version: "3.8"

networks:
  wardrobex-net:
    driver: bridge

services:
  # 新项目后端服务
  wardrobex_backend:
    build:
      context: ./PEFT_PROJECT
      dockerfile: Dockerfile
    ports:
      - "8011:8000"
    volumes:
      - /data/google/vit-base-patch16-224:/data/google/vit-base-patch16-224:ro
      - /data/Qwen3-0.6B:/data/Qwen3-0.6B:ro
    networks:
      - wardrobex-net

  # 新项目 nginx 服务，挂载前端和配置
  wardrobex_nginx:
    image: nginx:stable-alpine
    ports:
      - "8081:80"   # 端口别跟老项目冲突
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./PEFT_FRONTEND/dist:/usr/share/nginx/html/wardrobex:ro
    depends_on:
      - wardrobex_backend
    networks:
      - wardrobex-net
